# Generated by Django 5.2.15 on 2026-07-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_identity_canonicalization"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_recovery_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_restore_is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("deletion_recovery_deadline__isnull", True),
                        ("deletion_scheduled_at__isnull", True),
                    ),
                    models.Q(
                        ("deletion_recovery_deadline__isnull", False),
                        ("deletion_scheduled_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="accounts_user_deletion_timestamps_paired_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deletion_scheduled_at__isnull", True), ("is_active", False), _connector="OR"
                ),
                name="accounts_user_pending_deletion_implies_inactive_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("deletion_restore_is_active__isnull", True),
                        ("deletion_scheduled_at__isnull", True),
                    ),
                    models.Q(
                        ("deletion_restore_is_active__isnull", False),
                        ("deletion_scheduled_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="accounts_user_deletion_restore_flag_paired_ck",
            ),
        ),
    ]
