# Generated by Django 5.2.15 on 2026-08-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_timezone_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tag_default_color",
            field=models.CharField(
                choices=[
                    ("slate", "Slate"),
                    ("blue", "Blue"),
                    ("teal", "Teal"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("amber", "Amber"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("rose", "Rose"),
                    ("violet", "Violet"),
                    ("brown", "Brown"),
                ],
                default="slate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tag_semantic_color_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tag_uppercase_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tag_default_color__in",
                        (
                            "slate",
                            "blue",
                            "teal",
                            "green",
                            "yellow",
                            "amber",
                            "orange",
                            "red",
                            "rose",
                            "violet",
                            "brown",
                        ),
                    )
                ),
                name="accounts_user_tag_default_color_valid_ck",
            ),
        ),
    ]
