# Generated by Django 5.2.15 on 2026-08-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_userinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("warm-light", "Warm Light"), ("dark", "Dark")],
                default="warm-light",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("theme__in", ("warm-light", "dark"))),
                name="accounts_user_theme_valid_ck",
            ),
        ),
    ]
