# Generated by Django 5.2.15 on 2026-06-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body_json", models.JSONField()),
                ("body_plain_text", models.TextField()),
                ("editor_schema_version", models.PositiveIntegerField(default=1)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-modified_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["owner", "-modified_at"],
                name="notes_note_owner_i_c43444_idx",
            ),
        ),
    ]
