# Generated by Django 5.2.15 on 2026-07-04 18:32

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [models.OrderBy(django.db.models.functions.text.Lower("name"))],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="notes",
                to="notes.folder",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="notes_folder_name_not_blank_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("owner"),
                name="notes_folder_owner_name_ci_uq",
            ),
        ),
    ]
