# Generated by Django 5.2.15 on 2026-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_folder_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
