# Generated by Django 5.2.15 on 2026-07-10 13:55

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_note_pinned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("slate", "Slate"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("amber", "Amber"),
                            ("rose", "Rose"),
                            ("violet", "Violet"),
                        ],
                        default="slate",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [models.OrderBy(django.db.models.functions.text.Lower("name"))],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="notes", to="notes.tag"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="notes_tag_name_not_blank_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("owner"),
                name="notes_tag_owner_name_ci_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("color__in", ("slate", "blue", "green", "amber", "rose", "violet"))
                ),
                name="notes_tag_color_valid_ck",
            ),
        ),
    ]
