# Generated by Django 5.2.15 on 2026-07-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_tag_note_tags_tag_notes_tag_name_not_blank_ck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
