# Generated by Django 5.2.15 on 2026-07-13 13:13

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_note_trashed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="folder",
            name="notes_folder_owner_name_ci_uq",
        ),
        migrations.AddField(
            model_name="folder",
            name="trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("owner"),
                condition=models.Q(("trashed_at__isnull", True)),
                name="notes_folder_owner_name_ci_uq",
            ),
        ),
    ]
