# Generated by Django 5.2.15 on 2026-07-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0006_remove_folder_notes_folder_owner_name_ci_uq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="emptied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="emptied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
