# Generated by Django 5.2.15 on 2026-07-14 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0007_folder_emptied_at_note_emptied_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_recovery_folder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_recovery_folder", True)),
                fields=("owner",),
                name="notes_folder_owner_recovery_marker_uq",
            ),
        ),
    ]
