# Generated by Django 5.2.15 on 2026-07-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0008_folder_is_recovery_folder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="trashed_via_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trash_cascade_notes",
                to="notes.folder",
            ),
        ),
    ]
