# Generated by Django 5.2.15 on 2026-08-09 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0009_note_trashed_via_folder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="notes_tag_color_valid_ck",
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("slate", "Slate"),
                    ("blue", "Blue"),
                    ("teal", "Teal"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("amber", "Amber"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("rose", "Rose"),
                    ("violet", "Violet"),
                    ("brown", "Brown"),
                ],
                default="slate",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "color__in",
                        (
                            "slate",
                            "blue",
                            "teal",
                            "green",
                            "yellow",
                            "amber",
                            "orange",
                            "red",
                            "rose",
                            "violet",
                            "brown",
                        ),
                    )
                ),
                name="notes_tag_color_valid_ck",
            ),
        ),
    ]
